  - name: Pytest summary
  # You may pin to the exact commit or the version.
  # uses: dariocurr/pytest-summary@9235604fd8353b68d8bfdf5834ccf713c6016ddd
  uses: dariocurr/pytest-summary@v2.4
  with:
    # the pytest extensions to install along pytest
    extensions: # optional
    # the pytest options
    options: # optional
    # the path to the output file to create
    output: # optional
    # the path to the folder containing the tests
    paths: # optional, default is tests
    # which tests have to be shown in the summary
    show: # optional
          
